jobs:
- job: Build_Python
  timeoutInMinutes: 90
  pool:
    name: Azure Pipelines
    vmImage: $(VmImage)
  steps:
  # Temporary workaround until AGENT_TOOLSDIRECTORY is not set properly on Hosted Ubuntu 20.04 image
  - bash: |
      echo '##vso[task.setvariable variable=AGENT_TOOLSDIRECTORY]/opt/hostedtoolcache'
      mkdir -p /opt/hostedtoolcache
    displayName: 'set AGENT_TOOLSDIRECTORY variable'
    condition: eq(variables['Platform'], 'linux-20.04')

  - checkout: self
    submodules: true
    
  - task: PowerShell@2
    displayName: 'Build Python $(VERSION)'
    inputs:
      targetType: filePath
      filePath: './builders/build-python.ps1'
      arguments: '-Version $(VERSION) -Platform $(Platform) -Architecture $(Architecture)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: Python $(VERSION)'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'python-$(VERSION)-$(Platform)-$(Architecture)'